services:
  clsi:
    command: ["node", "--watch", "app.js"]
    environment:
      - NODE_OPTIONS=--inspect=0.0.0.0:9229
    ports:
      - "127.0.0.1:9230:9229"
    volumes:
      - /data_1/davrot/overleaf_dev/workspace/git-bridge/overleaf_with_admin_extension/services/clsi/app:/overleaf/services/clsi/app
      - /data_1/davrot/overleaf_dev/workspace/git-bridge/overleaf_with_admin_extension/services/clsi/app.js:/overleaf/services/clsi/app.js
      - /data_1/davrot/overleaf_dev/workspace/git-bridge/overleaf_with_admin_extension/services/clsi/config:/overleaf/services/clsi/config

  chat:
    command: ["node", "--watch", "app.js"]
    environment:
      - NODE_OPTIONS=--inspect=0.0.0.0:9229
    ports:
      - "127.0.0.1:9231:9229"
    volumes:
      - /data_1/davrot/overleaf_dev/workspace/git-bridge/overleaf_with_admin_extension/services/chat/app:/overleaf/services/chat/app
      - /data_1/davrot/overleaf_dev/workspace/git-bridge/overleaf_with_admin_extension/services/chat/app.js:/overleaf/services/chat/app.js
      - /data_1/davrot/overleaf_dev/workspace/git-bridge/overleaf_with_admin_extension/services/chat/config:/overleaf/services/chat/config

  contacts:
    command: ["node", "--watch", "app.js"]
    environment:
      - NODE_OPTIONS=--inspect=0.0.0.0:9229
    ports:
      - "127.0.0.1:9232:9229"
    volumes:
      - /data_1/davrot/overleaf_dev/workspace/git-bridge/overleaf_with_admin_extension/services/contacts/app:/overleaf/services/contacts/app
      - /data_1/davrot/overleaf_dev/workspace/git-bridge/overleaf_with_admin_extension/services/contacts/app.js:/overleaf/services/contacts/app.js
      - /data_1/davrot/overleaf_dev/workspace/git-bridge/overleaf_with_admin_extension/services/contacts/config:/overleaf/services/contacts/config

  docstore:
    command: ["node", "--watch", "app.js"]
    environment:
      - NODE_OPTIONS=--inspect=0.0.0.0:9229
    ports:
      - "127.0.0.1:9233:9229"
    volumes:
      - /data_1/davrot/overleaf_dev/workspace/git-bridge/overleaf_with_admin_extension/services/docstore/app:/overleaf/services/docstore/app
      - /data_1/davrot/overleaf_dev/workspace/git-bridge/overleaf_with_admin_extension/services/docstore/app.js:/overleaf/services/docstore/app.js
      - /data_1/davrot/overleaf_dev/workspace/git-bridge/overleaf_with_admin_extension/services/docstore/config:/overleaf/services/docstore/config

  document-updater:
    command: ["node", "--watch", "app.js"]
    environment:
      - NODE_OPTIONS=--inspect=0.0.0.0:9229
    ports:
      - "127.0.0.1:9234:9229"
    volumes:
      - /data_1/davrot/overleaf_dev/workspace/git-bridge/overleaf_with_admin_extension/services/document-updater/app:/overleaf/services/document-updater/app
      - /data_1/davrot/overleaf_dev/workspace/git-bridge/overleaf_with_admin_extension/services/document-updater/app.js:/overleaf/services/document-updater/app.js
      - /data_1/davrot/overleaf_dev/workspace/git-bridge/overleaf_with_admin_extension/services/document-updater/config:/overleaf/services/document-updater/config

  filestore:
    command: ["node", "--watch", "app.js"]
    environment:
      - NODE_OPTIONS=--inspect=0.0.0.0:9229
    ports:
      - "127.0.0.1:9235:9229"
    volumes:
      - /data_1/davrot/overleaf_dev/workspace/git-bridge/overleaf_with_admin_extension/services/filestore/app:/overleaf/services/filestore/app
      - /data_1/davrot/overleaf_dev/workspace/git-bridge/overleaf_with_admin_extension/services/filestore/app.js:/overleaf/services/filestore/app.js
      - /data_1/davrot/overleaf_dev/workspace/git-bridge/overleaf_with_admin_extension/services/filestore/config:/overleaf/services/filestore/config

  history-v1:
    command: ["node", "--watch", "app.js"]
    environment:
      - NODE_OPTIONS=--inspect=0.0.0.0:9229
    ports:
      - "127.0.0.1:9239:9229"
    volumes:
      - /data_1/davrot/overleaf_dev/workspace/git-bridge/overleaf_with_admin_extension/services/history-v1/api:/overleaf/services/history-v1/api
      - /data_1/davrot/overleaf_dev/workspace/git-bridge/overleaf_with_admin_extension/services/history-v1/app.js:/overleaf/services/history-v1/app.js
      - /data_1/davrot/overleaf_dev/workspace/git-bridge/overleaf_with_admin_extension/services/history-v1/config:/overleaf/services/history-v1/config
      - /data_1/davrot/overleaf_dev/workspace/git-bridge/overleaf_with_admin_extension/services/history-v1/storage:/overleaf/services/history-v1/storage
      - /data_1/davrot/overleaf_dev/workspace/git-bridge/overleaf_with_admin_extension/services/history-v1/knexfile.js:/overleaf/services/history-v1/knexfile.js
      - /data_1/davrot/overleaf_dev/workspace/git-bridge/overleaf_with_admin_extension/services/history-v1/migrations:/overleaf/services/history-v1/migrations

  notifications:
    command: ["node", "--watch", "app.ts"]
    environment:
      - NODE_OPTIONS=--inspect=0.0.0.0:9229
    ports:
      - "127.0.0.1:9236:9229"
    volumes:
      - /data_1/davrot/overleaf_dev/workspace/git-bridge/overleaf_with_admin_extension/services/notifications/app:/overleaf/services/notifications/app
      - /data_1/davrot/overleaf_dev/workspace/git-bridge/overleaf_with_admin_extension/services/notifications/app.ts:/overleaf/services/notifications/app.ts
      - /data_1/davrot/overleaf_dev/workspace/git-bridge/overleaf_with_admin_extension/services/notifications/config:/overleaf/services/notifications/config

  project-history:
    command: ["node", "--watch", "app.js"]
    environment:
      - NODE_OPTIONS=--inspect=0.0.0.0:9229
    ports:
      - "127.0.0.1:9240:9229"
    volumes:
      - /data_1/davrot/overleaf_dev/workspace/git-bridge/overleaf_with_admin_extension/services/project-history/app:/overleaf/services/project-history/app
      - /data_1/davrot/overleaf_dev/workspace/git-bridge/overleaf_with_admin_extension/services/project-history/app.js:/overleaf/services/project-history/app.js
      - /data_1/davrot/overleaf_dev/workspace/git-bridge/overleaf_with_admin_extension/services/project-history/config:/overleaf/services/project-history/config

  real-time:
    command: ["node", "--watch", "app.js"]
    environment:
      - NODE_OPTIONS=--inspect=0.0.0.0:9229
    ports:
      - "127.0.0.1:9237:9229"
    volumes:
      - /data_1/davrot/overleaf_dev/workspace/git-bridge/overleaf_with_admin_extension/services/real-time/app:/overleaf/services/real-time/app
      - /data_1/davrot/overleaf_dev/workspace/git-bridge/overleaf_with_admin_extension/services/real-time/app.js:/overleaf/services/real-time/app.js
      - /data_1/davrot/overleaf_dev/workspace/git-bridge/overleaf_with_admin_extension/services/real-time/config:/overleaf/services/real-time/config

  web:
    command: ["node", "--watch", "app.mjs", "--watch-locales"]
    environment:
      - NODE_OPTIONS=--inspect=0.0.0.0:9229
    ports:
      - "127.0.0.1:9229:9229"
    volumes:
      - /data_1/davrot/overleaf_dev/workspace/git-bridge/overleaf_with_admin_extension/services/web/app:/overleaf/services/web/app
      - /data_1/davrot/overleaf_dev/workspace/git-bridge/overleaf_with_admin_extension/services/web/app.mjs:/overleaf/services/web/app.mjs
      - /data_1/davrot/overleaf_dev/workspace/git-bridge/overleaf_with_admin_extension/services/web/config:/overleaf/services/web/config
      - /data_1/davrot/overleaf_dev/workspace/git-bridge/overleaf_with_admin_extension/services/web/locales:/overleaf/services/web/locales
      - /data_1/davrot/overleaf_dev/workspace/git-bridge/overleaf_with_admin_extension/services/web/modules:/overleaf/services/web/modules
      - /data_1/davrot/overleaf_dev/workspace/git-bridge/overleaf_with_admin_extension/services/web/public:/overleaf/services/web/public

  webpack:
    volumes:
      - /data_1/davrot/overleaf_dev/workspace/git-bridge/overleaf_with_admin_extension/services/web/app:/overleaf/services/web/app
      - /data_1/davrot/overleaf_dev/workspace/git-bridge/overleaf_with_admin_extension/services/web/config:/overleaf/services/web/config
      - /data_1/davrot/overleaf_dev/workspace/git-bridge/overleaf_with_admin_extension/services/web/frontend:/overleaf/services/web/frontend
      - /data_1/davrot/overleaf_dev/workspace/git-bridge/overleaf_with_admin_extension/services/web/locales:/overleaf/services/web/locales
      - /data_1/davrot/overleaf_dev/workspace/git-bridge/overleaf_with_admin_extension/services/web/modules:/overleaf/services/web/modules
      - /data_1/davrot/overleaf_dev/workspace/git-bridge/overleaf_with_admin_extension/services/web/public:/overleaf/services/web/public
      - /data_1/davrot/overleaf_dev/workspace/git-bridge/overleaf_with_admin_extension/services/web/transform:/overleaf/services/web/transform
      - /data_1/davrot/overleaf_dev/workspace/git-bridge/overleaf_with_admin_extension/services/web/types:/overleaf/services/web/types
      - /data_1/davrot/overleaf_dev/workspace/git-bridge/overleaf_with_admin_extension/services/web/webpack-plugins:/overleaf/services/web/webpack-plugins
