name: "CI: Go Contacts Service"

on:
  push:
    paths:
      - "services/contacts/**"
  pull_request:
    paths:
      - "services/contacts/**"

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - name: Run go vet
        run: |
          cd services/contacts
          go vet ./...
      - name: Run tests
        run: |
          cd services/contacts
          go test ./...
