name: "CI: Go Docstore Service"

on:
  push:
    paths:
      - "services/docstore/**"
  pull_request:
    paths:
      - "services/docstore/**"

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.25"
      - name: Run go vet
        run: |
          cd services/docstore
          go vet ./...
      - name: Run tests
        run: |
          cd services/docstore
          go test ./...
